Repository vtothsvk/AP-Home, pull requests merged in 2020-11, with the labels that each got.

#33 Motion toggle
  AP_Nurse.cpp
  Sensor_enable.h
Labels: FW, bugFix, enhancement

#34 Fixed docummentation
  Documentation/Programming.md
  README.md
Labels: documentation

#39 Added sensor enable directives and rebuilt sensor data printout
  AP-Home.ino
  AP_Nurse.cpp
  AP_Nurse.h
  Sensor_enable.h
Labels: enhancement

#45 Pairing window + periodic RF data advertisement
  AP-Home.ino
Labels: FW, bugFix

#51 Update GIT.md
  Documentation/GIT.md
Labels: documentation

#41 Bme
  AP_Nurse.cpp
  AP_Nurse.h
  AP_Nurse_types.h
Labels: FW, enhancement

#61 added bme enable directive and complete bme data printout
  AP_Nurse.cpp
  Sensor_enable.h
Labels: FW, enhancement
